### ISSUE TITLE
pvoutput 400 bad request

### ISSUE THREAD

**Issue by rwrw01** [ruddj/sdm630-report#3]
uploading the values to PvOutput give a 400 error without a reason stated.

I reformated the complete url to a regular curl url just to test and get a reason. When I read the specs of the API a number of things are different:

values are stated as 
'v1' :  <value> 
and not als 
'v1=<value>'
and the date and time are between quotes. The output doesn't seem to follow the specs off the API ?

working URL:
curl -d "v6=226.62" -d "t=11:00" -d "v8=119.838" -d "c1=1" -d "v7=-2612.467" -d "d=20170819" -d "v4=-2346" -d "v3=112" -d "v9=146.424" -H "X-Pvoutput-Apikey: -----" -H "X-Pvoutput-SystemId: -----" https://pvoutput.org/service/r2/addstatus.jsp 

not working (used by script):
'X-Pvoutput-SystemId': '------', 'X-Pvoutput-Apikey': '---------'
'v6': 226.62, 't': '11:00', 'v8': 119.838, 'c1': 1, 'v7': -2612.467, 'd': '20170819', 'v4': -2346, 'v3': 112, 'v9': 146.424}

**Comment by ruddj** [comment]
Hi Ralph, 
Please read up on how how Python Requests module works. You create dict key/value pairs and it converts them to POST data. The 'v1' : entry is a key value pair, the key is v1 and the value is what is read from data file. 
The message that is printed when you run pvoutput.py with verbose=1 is just showing you the contents of the arrays, these are then formatted by Requests before being sent to PVOutput.
http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests

Just to confirm you have set PVAPI and SystemID in the /etc/sdm630.conf? 
Are you a PVOutput Donor? If not make sure you set PVextend to False as these options only work for donors.
Set VERBOSE = 2 to see even more debug when script runs in python script.

Good Luck,
 James

**Comment by rwrw01** [comment]
Hi James,
yes the pvapi and systemid are filled. I'll read up on requests. Obvious not to much experience with python requests :). I'll fiddle some more

**Comment by ruddj** [comment]
When the script fails it should print out a more detailed error message in addition to the 400 error code. (The r.reason) line. Can you please copy the full error message to try to determine why the server considers the request invalid?

Also are you a PVOutput donor? That effects which values can be uploaded.

**Comment by rwrw01** [comment]
I gives this:

Opening file: /var/tmp/ACT-2017-08-19-15-46.sdm
{'X-Pvoutput-SystemId': '53848', 'X-Pvoutput-Apikey': '-------------'}
{'v4': -1164, 'c1': 1, 'v3': 113504, 'v9': 0.0, 't': '15:46', 'v7': -1276.638, 'd': '20170819', 'v8': 112.475, 'v6': 227.46}
400 Bad Request

When I run the values in curl (manually created the command) the error messages give more information:
"Bad request 400: Invalid power value".  
everything after the ":" seems to be lost when running the post through requests.

The negative v4 value seems to be the problem (though it should not be a problem). V4 is negative because of the PV, this is not a script problem though.

**Comment by ruddj** [comment]
I think you are right about the problem. I have my meter between my load and my PV, so it is never negative. e.g. House Switchboard -> SDM630 -> PV (Meterbox) -> Utility Meter
If generating it should probably be putting the positive value to v2 instead of negative v4. 

How do you have it hooked up? Is it only monitoring your PV or your household usage as well?
If monitoring everything do you have any other way to monitor PV? The main thing is if it is the only monitoring there is no way to separate total generation vs net generation (after usage).
You can add the value n=1 to say these are net values rather than gross values, but would need to be uploading generation data to PVOutput as well for it to perform a calculation for true consumption.

We can easily change the logic of what values are sent, but I need to know how it is hooked up and what data you want to log.

**Comment by rwrw01** [comment]
The SDM is monitoring the complete household. I cannot hook it up any different, I have the exact generation though from the invertor. I can subtract the generation from the import en compensatie for export getting the real values, the PV is hooked up on one phase. I already have a pyhton script reading the invertor values.

I'll close the issue since this is more a pvoutput thing, It is weird that the bad request reason isn fully shown though,

**Comment by ruddj** [comment]
Hi Ralph,
 I was not suggesting changing the wiring, just trying to figure out how you have things set up and what data you have access to.
As you have the PV and Consumption both passing through meter you should enable the n=1 flag to report it is net rather than gross value. 
Also to troubleshoot try running script at night when there is no generation. If this works you know that the negative value is problem, if not it could be something else.

Finally you have never answered if you are a donor or not. As mentioned here https://pvoutput.org/help.html#donations-app-bonus only donors have access to Extended data, trying to use this without donor access will give a 400 error as well. If not you need to set PVextend to False.

**Comment by rwrw01** [comment]
Hi james, 

I'm a donator for pvoutput so the extended values should be excepted

**Comment by rwrw01** [comment]
checked a number of values tot see where the 400-error came from. Concrete:
c1, gives a error 400
v3, gives a error 400, value is IMPO_WH: 136.244995

concerning v3, the script multiplies the value with 1000. It states
        # Watt Hours, Cumulative energy usage
        # Multiply by 1000 as in kW
        dEnergyCon = round( sdmdata.getfloat('MODBUS','IMPO_WH') * 1000)
I the meter would read kW I would expect dividing with 1000 ? The pvoutput helpfile stats that this value should be Wh, not kWh ?

**Comment by ruddj** [comment]
Metric:  2.3 kWh = 2300 Wh, So if meter is reading in kWh and PVOutput wants Wh you multiply by 1000.

From memory part of the problem is v3 does not like decimals. It only wanted a whole number as a fraction of a watt is too small to care about.
